start 'MyNextKey.sql'
start 'CloseCalls.sql'
start 'CheckCallOnUpdate.sql'
start 'CheckTaskOnUpdate.sql'
start 'AuditAccountingCodeDelete.sql'
start 'AuditAccountingCodeInsert.sql'
start 'AuditAccountingCodeUpdate.sql'
start 'AuditCategoryDelete.sql'
start 'AuditCategoryInsert.sql'
start 'AuditCategoryProcessDelete.sql'
start 'AuditCategoryProcessInsert.sql'
start 'AuditCategoryProcessUpdate.sql'
start 'AuditCategoryUpdate.sql'
start 'AuditContractDelete.sql'
start 'AuditContractInsert.sql'
start 'AuditContractUpdate.sql'
start 'AuditOrganizationDelete.sql'
start 'AuditOrganizationInsert.sql'
start 'AuditOrganizationUpdate.sql'
start 'AuditProcessDelete.sql'
start 'AuditProcessInsert.sql'
start 'AuditProcessUpdate.sql'
start 'AuditGroupmemberDelete.sql'
start 'AuditGroupmemberInsert.sql'
start 'AuditGroupmemberUpdate.sql'
start 'AuditWorkgroupDelete.sql'
start 'AuditWorkgroupHwgDelete.sql'
start 'AuditWorkgroupHwgInsert.sql'
start 'AuditWorkgroupInsert.sql'
start 'AuditWorkgroupUpdate.sql'
start 'AuditHwgTasktypeDelete.sql'
start 'AuditHwgTasktypeInsert.sql'
start 'AuditEmployeeUpdate.sql'
start 'AuditExtSystemInsert.sql'
start 'AuditExtSystemUpdate.sql'
start 'AuditExtSystemDelete.sql'
start 'SMC_TASK_TRG.sql'
start 'TransmitTasksOnCallCloseUpdate.sql'
start 'UpdateLocationDescOnInsert.sql'
start 'UpdateLocationDescOnUpdate.sql'
start 'UpdateCountersOnTaskUpdate.sql'
start 'UpdateCountersOnTaskInsert.sql'
start 'SetCallTimestampsOnStatusUpdate.sql'
start 'UpdateEffortOnCallUpdate.sql'
start 'UpdateEmployeeOnInsertOrUpdate.sql'
-- start 'q_drop_lock.sql'


disconnect
exit
