/*******************************************************************************
 *    This file is part of Open-jACOB
 *    Copyright (C) 2005-2006 Tarragon GmbH
 * 
 *    This program is free software; you can redistribute it and/or modify
 *    it under the terms of the GNU General Public License as published by
 *    the Free Software Foundation; version 2 of the License.
 * 
 *    This program is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *    GNU General Public License for more details.
 * 
 *    You should have received a copy of the GNU General Public License     
 *    along with this program; if not, write to the Free Software
 *    Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  
 *    USA
 *******************************************************************************/

package de.tif.jacob.core.data.impl.sql;

import de.tif.jacob.core.data.impl.IDataSource;
import de.tif.jacob.core.definition.FieldType;
import de.tif.jacob.core.schema.ISchemaColumnDefinition;

/**
 * SQL data source interface providing all relevant methods for implementation
 * of {@link ISchemaColumnDefinition}.
 * 
 * @see ISchemaColumnDefinition#getSQLType(ISQLDataSource)
 * @see ISchemaColumnDefinition#getSQLSize(ISQLDataSource)
 * @see ISchemaColumnDefinition#getSQLDecimalDigits(ISQLDataSource)
 * @see ISchemaColumnDefinition#isDBAutoGenerated(ISQLDataSource)
 * 
 * @author Andreas Sonntag
 */
public interface ISQLDataSource extends IDataSource
{
  /**
   * Determines whether for the given field type mapping of long text values
   * (e.g. values are in jacob_text table) is needed.
   * 
   * @param fieldType
   *          the field type to check mapping
   * @return <code>true</code> mapping is needed, otherwise <code>false</code>
   */
  public boolean needsMappingOfLongText(FieldType fieldType);
  
  /**
   * Determines whether for the given field type mapping of binary values (e.g.
   * values are in jacob_binary table) is needed.
   * 
   * @param fieldType
   *          the field type to check mapping
   * @return <code>true</code> mapping is needed, otherwise <code>false</code>
   */
  public boolean needsMappingOfBinary(FieldType fieldType);
  
  /**
   * Returns the default SQL type for long text fields.
   * 
   * @return the default long text SQL type.
   * @since 2.8.7
   * @see java.sql.Types
   */
  public int getDefaultLongTextSQLType();
  
  /**
   * Returns the default SQL type for binary fields.
   * 
   * @return the default binary SQL type.
   * @since 2.8.7
   * @see java.sql.Types
   */
  public int getDefaultBinarySQLType();
}
