package de.shorti.baseknowledge.objects;

/**
 * Class generated by automatic ClassGenerator
 * Date: Sat May 11 21:15:23 GMT+02:00 2002
 */
import de.shorti.db.*;
import java.util.ArrayList;
import java.util.Iterator;
import java.sql.*;

class _dbAddress extends dbObject 
{

	String    zipCode_id;	// Foreign Key pointing to Table [ZipCode], Field [id]
	String    number;
	String    street;


	/**
	 * destroy a object in the database
	 */
	public boolean destroy()
	{
		boolean result = false;
		String    _key   = id;
		SaveStatement  stmt;

		try
		{
			stmt  = ConnectionManager.getValid().createStatement("_dbAddress.destroyInstance");
			try
			{
					stmt.executeUpdate( "DELETE FROM Address WHERE id='"+_key+"'");
					result = true;
					removeFromCache(this);
					id     = null;
			}
			catch(Exception exc)
			{
				System.err.println(exc);
				exc.printStackTrace();
			}
			stmt.close();
		
		}
		catch (Exception ex)
		{
			System.err.println(ex);
			ex.printStackTrace();
		}
		return result;
	}



	/**
	 * Method:      getNumber()
	 * Description: 
	 * Returns:     String
	 */
	public String getNumber()
	{
		return number;
	}

	/**
	 * Method:      setNumber(String _number, boolean _autoCommit)
	 * Description: 
	 * Returns:     void
	 */
	public void setNumber(String _number, boolean _autoCommit)
	{
		number=_number;
		if(_autoCommit)
		{
			commit();
		}
	}

	/**
	 * Method:      getStreet()
	 * Description: 
	 * Returns:     String
	 */
	public String getStreet()
	{
		return street;
	}

	/**
	 * Method:      setStreet(String _street, boolean _autoCommit)
	 * Description: 
	 * Returns:     void
	 */
	public void setStreet(String _street, boolean _autoCommit)
	{
		street=_street;
		if(_autoCommit)
		{
			commit();
		}
	}

	/**
	 * Method:      getId()
	 * Description: 
	 * Returns:     String
	 */
	public String getId()
	{
		return id;
	}

	/**
	 * Method:      getZipCode()
	 * Description: 
	 * Returns:     ZipCode
	 */
	public ZipCode getZipCode()
	{
		return ZipCode.findById(zipCode_id);
	}

	/**
	 * Method:      setZipCode()
	 * Description: 
	 * Returns:     void
	 */
	public void setZipCode(ZipCode _foreigner, boolean _autocommit)
	{
		zipCode_id= _foreigner.getId();
		if (_autocommit == true)
			commit();
	}

	/**
	 *  Method:      getGeschaeftsstelles()
	 *  Description:                              
	 *  Returns:     ArrayList<Geschaeftsstelle>
	 */
	public ArrayList getGeschaeftsstelles()
	{
		return _dbGeschaeftsstelle.findByAddress(this);
	}


	/**
	 *  Method:      findByZipCode(_dbZipCode _zipCode)
	 *  Description: 
	 *  Returns:     ArrayList<Address>
	 */
	public static ArrayList findByZipCode(_dbZipCode _zipCode)
	{
		ArrayList result = new ArrayList();
		SaveStatement  stmt;

		try
		{
			stmt  = ConnectionManager.getValid().createStatement("_dbAddress.findByZipCode");
			try
			{
				ResultSet s = stmt.executeQuery( "SELECT id, zipCode_id, number, street FROM Address WHERE zipCode_id='"+toSQL(((_zipCode==null)?"":_zipCode.getId()))+"'"+" order by generatedId desc");
				while(s.next())
				{
					String _tmpID = s.getString(1);
					Address newObject = (Address)getFromCache(_tmpID);
					if(newObject ==null)
					{
						newObject = new Address();
						newObject.zipCode_id=s.getString(2);
						newObject.number=s.getString(3);
						newObject.street=s.getString(4);
						newObject.id=_tmpID;
						putToCache(newObject);
					}
					result.add(newObject);
				}
			}
			catch(Exception exc)
			{
				System.err.println(exc);
				exc.printStackTrace();
			}
			stmt.close();
		
		}
		catch (Exception ex)
		{
			System.err.println(ex);
			ex.printStackTrace();
		}
		return result;
	}

	/**
	 *  Method:      findByNumber(String _number)
	 *  Description: 
	 *  Returns:     ArrayList<Address>
	 */
	public static ArrayList findByNumber(String _number)
	{
		ArrayList result = new ArrayList();
		SaveStatement  stmt;

		try
		{
			stmt  = ConnectionManager.getValid().createStatement("_dbAddress.findByNumber");
			try
			{
				ResultSet s = stmt.executeQuery( "SELECT id, zipCode_id, number, street FROM Address WHERE number='"+toSQL(_number)+"'"+" order by generatedId desc");
				while(s.next())
				{
					String _tmpID = s.getString(1);
					Address newObject = (Address)getFromCache(_tmpID);
					if(newObject ==null)
					{
						newObject = new Address();
						newObject.zipCode_id=s.getString(2);
						newObject.number=s.getString(3);
						newObject.street=s.getString(4);
						newObject.id=_tmpID;
						putToCache(newObject);
					}
					result.add(newObject);
				}
			}
			catch(Exception exc)
			{
				System.err.println(exc);
				exc.printStackTrace();
			}
			stmt.close();
		
		}
		catch (Exception ex)
		{
			System.err.println(ex);
			ex.printStackTrace();
		}
		return result;
	}

	/**
	 *  Method:      findByStreet(String _street)
	 *  Description: 
	 *  Returns:     ArrayList<Address>
	 */
	public static ArrayList findByStreet(String _street)
	{
		ArrayList result = new ArrayList();
		SaveStatement  stmt;

		try
		{
			stmt  = ConnectionManager.getValid().createStatement("_dbAddress.findByStreet");
			try
			{
				ResultSet s = stmt.executeQuery( "SELECT id, zipCode_id, number, street FROM Address WHERE street='"+toSQL(_street)+"'"+" order by generatedId desc");
				while(s.next())
				{
					String _tmpID = s.getString(1);
					Address newObject = (Address)getFromCache(_tmpID);
					if(newObject ==null)
					{
						newObject = new Address();
						newObject.zipCode_id=s.getString(2);
						newObject.number=s.getString(3);
						newObject.street=s.getString(4);
						newObject.id=_tmpID;
						putToCache(newObject);
					}
					result.add(newObject);
				}
			}
			catch(Exception exc)
			{
				System.err.println(exc);
				exc.printStackTrace();
			}
			stmt.close();
		
		}
		catch (Exception ex)
		{
			System.err.println(ex);
			ex.printStackTrace();
		}
		return result;
	}

	/**
	 *  Method:      findById(String _id)
	 *  Description: 
	 *  Returns:     Address
	 */
	public static Address findById(String _id)
	{
		Address result = (Address)getFromCache(_id);
		if(result!=null) return result;
		SaveStatement  stmt;

		try
		{
			stmt  = ConnectionManager.getValid().createStatement("_dbAddress.findById");
			try
			{
				ResultSet s = stmt.executeQuery( "SELECT id, zipCode_id, number, street FROM Address WHERE id='"+toSQL(_id)+"'"+" order by generatedId desc");
				if(s.next())
				{
					result = new Address();
					result.zipCode_id= s.getString(2);
					result.number= s.getString(3);
					result.street= s.getString(4);
					result.id= _id;
					putToCache(result);
				}
			}
			catch(Exception exc)
			{
				System.err.println(exc);
				exc.printStackTrace();
			}
			stmt.close();
		
		}
		catch (Exception ex)
		{
			System.err.println(ex);
			ex.printStackTrace();
		}
		return result;
	}

	/**
	 * returns boolean
	 */
	public boolean commit()
	{
		SaveStatement  stmt;

		try
		{
			stmt  = ConnectionManager.getValid().createStatement("_dbAddress.commit");
			try
			{
				stmt.executeUpdate( "UPDATE Address set zipCode_id= '"+toSQL(zipCode_id)+"', number= '"+toSQL(number)+"', street= '"+toSQL(street)+"' WHERE id='"+id+"'");
			}
			catch(Exception exc)
			{
				System.err.println(exc);
				exc.printStackTrace();
			}
			stmt.close();
		
		}
		catch (Exception ex)
		{
			System.err.println(ex);
			ex.printStackTrace();
		}
		return true;
	}


	/**
	 * returns ArrayList<Address>
	 */
	public static ArrayList getAll()
	{
		ArrayList result = new ArrayList();
		SaveStatement  stmt;

		try
		{
			stmt  = ConnectionManager.getValid().createStatement("_dbAddress.getAll");
			try
			{
				ResultSet s = stmt.executeQuery( "SELECT id, zipCode_id, number, street FROM Address order by generatedId desc");
				while(s.next())
				{
					String _tmpID = s.getString(1);
					Address newObject = (Address)getFromCache(_tmpID);
					if(newObject ==null)
					{
						newObject = new Address();
						newObject.zipCode_id=s.getString(2);
						newObject.number=s.getString(3);
						newObject.street=s.getString(4);
						newObject.id=_tmpID;
						putToCache(newObject);
					}
					result.add(newObject);
				}
			}
			catch(Exception exc)
			{
				System.err.println(exc);
				exc.printStackTrace();
			}
			stmt.close();
		
		}
		catch (Exception ex)
		{
			System.err.println(ex);
			ex.printStackTrace();
		}
		return result;
	}


	/**
	 * create a new object in the database
	 */
	static public Address createInstance( _dbZipCode _zipCode, String  _number, String  _street )
	{
		Address result = null;
		SaveStatement  stmt;

		try
		{
			stmt  = ConnectionManager.getValid().createStatement("_dbAddress.createInstance");
			try
			{
				String nextGUID = new java.rmi.server.UID().toString();
				stmt.executeUpdate( "INSERT INTO Address ( zipCode_id, number, street, id) VALUES ( '"+((_zipCode==null)?"":_zipCode.getId())+"',  '"+toSQL(_number)+"',  '"+toSQL(_street)+"', '"+nextGUID+"')");
				result = new Address();
				result.zipCode_id= (_zipCode==null)?"":_zipCode.getId();
				result.number= _number;
				result.street= _street;
				result.id= nextGUID;
			}
			catch(Exception exc)
			{
				System.err.println(exc);
				exc.printStackTrace();
			}
			stmt.close();
		
		}
		catch (Exception ex)
		{
			System.err.println(ex);
			ex.printStackTrace();
		}
		return result;
	}


	/**
	 * create a new object in the database
	 */
	static public void newInstance( _dbZipCode _zipCode, String  _number, String  _street )
	{
		SaveStatement  stmt;

		try
		{
			stmt  = ConnectionManager.getValid().createStatement("_dbAddress.newInstance");
			try
			{
				String nextGUID = new java.rmi.server.UID().toString();
				stmt.executeUpdate( "INSERT INTO Address ( zipCode_id, number, street, id) VALUES ( '"+((_zipCode==null)?"":_zipCode.getId())+"',  '"+toSQL(_number)+"',  '"+toSQL(_street)+"', '"+nextGUID+"')");
			}
			catch(Exception exc)
			{
				System.err.println(exc);
				exc.printStackTrace();
			}
			stmt.close();
		
		}
		catch (Exception ex)
		{
			System.err.println(ex);
			ex.printStackTrace();
		}
	}


	/**
	 * destroy a object in the database
	 */
	static public boolean destroyInstance( String  _key)
	{
		boolean result = false;
		SaveStatement  stmt;

		try
		{
			stmt  = ConnectionManager.getValid().createStatement("_dbAddress.destroyInstance");
			try
			{
					stmt.executeUpdate( "DELETE FROM Address WHERE id='"+_key+"'");
					result = true;
			}
			catch(Exception exc)
			{
				System.err.println(exc);
				exc.printStackTrace();
			}
			stmt.close();
		
		}
		catch (Exception ex)
		{
			System.err.println(ex);
			ex.printStackTrace();
		}
		return result;
	}


	/**
	 * destroy ALL objects in the database
	 */
	static public boolean destroyAll()
	{
		boolean result = false;
		SaveStatement  stmt;

		try
		{
			stmt  = ConnectionManager.getValid().createStatement("_dbAddress.destroyAll");
			try
			{
					stmt.executeUpdate("DELETE from Address" );
					result = true;
			}
			catch(Exception exc)
			{
				System.err.println(exc);
				exc.printStackTrace();
			}
			stmt.close();
		
		}
		catch (Exception ex)
		{
			System.err.println(ex);
			ex.printStackTrace();
		}
		return result;
	}


	/**
	 */
	public String toString()
	{
		StringBuffer result = new StringBuffer(1024);
		result.append(zipCode_id);
		result.append("|");
		result.append(number);
		result.append("|");
		result.append(street);
		result.append("|");
		result.append(id);
		return result.toString();
	}


	/**
	 * init the class
	 */
	static
	{
		try
		{
			DatabaseMetaData dMeta = ConnectionManager.getValid().getMetaData ();
			ResultSet result;
			result=dMeta.getColumns(null,null,"Address","zipCode_id");
			if(!result.next())
			{
				System.out.println("ERROR: installed DB-schema not compatible to java classes");
				System.out.println("       Attribute 'zipCode_id' in table 'Address' missing");
			}
			result.close();
			result=dMeta.getColumns(null,null,"Address","number");
			if(!result.next())
			{
				System.out.println("ERROR: installed DB-schema not compatible to java classes");
				System.out.println("       Attribute 'number' in table 'Address' missing");
			}
			result.close();
			result=dMeta.getColumns(null,null,"Address","street");
			if(!result.next())
			{
				System.out.println("ERROR: installed DB-schema not compatible to java classes");
				System.out.println("       Attribute 'street' in table 'Address' missing");
			}
			result.close();
			result=dMeta.getColumns(null,null,"Address","id");
			if(!result.next())
			{
				System.out.println("ERROR: installed DB-schema not compatible to java classes");
				System.out.println("       Attribute 'id' in table 'Address' missing");
			}
			result.close();
		}
		catch (Exception ex)
		{
		}
	}


}
