package de.shorti.baseknowledge.objects;

/**
 * Class generated by automatic ClassGenerator
 * Date: Sat May 11 21:15:21 GMT+02:00 2002
 */
import java.sql.DatabaseMetaData;
import java.sql.ResultSet;
import java.util.ArrayList;

class _dbCity extends dbObject 
{

	String    state_id;	// Foreign Key pointing to Table [State], Field [id]
	String    name;
	String    dialPrefix;


	/**
	 * destroy a object in the database
	 */
	public boolean destroy()
	{
		boolean result = false;
		String    _key   = id;
		SaveStatement  stmt;

		try
		{
			stmt  = ConnectionManager.getValid().createStatement("_dbCity.destroyInstance");
			try
			{
					stmt.executeUpdate( "DELETE FROM City WHERE id='"+_key+"'");
					result = true;
					removeFromCache(this);
					id     = null;
			}
			catch(Exception exc)
			{
				System.err.println(exc);
				exc.printStackTrace();
			}
			stmt.close();
		
		}
		catch (Exception ex)
		{
			System.err.println(ex);
			ex.printStackTrace();
		}
		return result;
	}



	/**
	 * Method:      getName()
	 * Description: 
	 * Returns:     String
	 */
	public String getName()
	{
		return name;
	}

	/**
	 * Method:      setName(String _name, boolean _autoCommit)
	 * Description: 
	 * Returns:     void
	 */
	public void setName(String _name, boolean _autoCommit)
	{
		name=_name;
		if(_autoCommit)
		{
			commit();
		}
	}

	/**
	 * Method:      getDialPrefix()
	 * Description: 
	 * Returns:     String
	 */
	public String getDialPrefix()
	{
		return dialPrefix;
	}

	/**
	 * Method:      setDialPrefix(String _dialPrefix, boolean _autoCommit)
	 * Description: 
	 * Returns:     void
	 */
	public void setDialPrefix(String _dialPrefix, boolean _autoCommit)
	{
		dialPrefix=_dialPrefix;
		if(_autoCommit)
		{
			commit();
		}
	}

	/**
	 * Method:      getId()
	 * Description: 
	 * Returns:     String
	 */
	public String getId()
	{
		return id;
	}

	/**
	 * Method:      getState()
	 * Description: 
	 * Returns:     State
	 */
	public State getState()
	{
		return State.findById(state_id);
	}

	/**
	 * Method:      setState()
	 * Description: 
	 * Returns:     void
	 */
	public void setState(State _foreigner, boolean _autocommit)
	{
		state_id= _foreigner.getId();
		if (_autocommit == true)
			commit();
	}

	/**
	 *  Method:      getAirports()
	 *  Description:                              
	 *  Returns:     ArrayList<Airport>
	 */
	public ArrayList getAirports()
	{
		return _dbAirport.findByCity(this);
	}


	/**
	 *  Method:      getCountries()
	 *  Description:                              
	 *  Returns:     ArrayList<Country>
	 */
	public ArrayList getCountries()
	{
		return _dbCountry.findByCapital(this);
	}


	/**
	 *  Method:      getStates()
	 *  Description:                              
	 *  Returns:     ArrayList<State>
	 */
	public ArrayList getStates()
	{
		return _dbState.findByCapital(this);
	}


	/**
	 *  Method:      getZipCodes()
	 *  Description:                              
	 *  Returns:     ArrayList<ZipCode>
	 */
	public ArrayList getZipCodes()
	{
		return _dbZipCode.findByCity(this);
	}


	/**
	 *  Method:      findByState(_dbState _state)
	 *  Description: 
	 *  Returns:     ArrayList<City>
	 */
	public static ArrayList findByState(_dbState _state)
	{
		ArrayList result = new ArrayList();
		SaveStatement  stmt;

		try
		{
			stmt  = ConnectionManager.getValid().createStatement("_dbCity.findByState");
			try
			{
				ResultSet s = stmt.executeQuery( "SELECT id, state_id, name, dialPrefix FROM City WHERE state_id='"+toSQL(((_state==null)?"":_state.getId()))+"'"+" order by generatedId desc");
				while(s.next())
				{
					String _tmpID = s.getString(1);
					City newObject = (City)getFromCache(_tmpID);
					if(newObject ==null)
					{
						newObject = new City();
						newObject.state_id=s.getString(2);
						newObject.name=s.getString(3);
						newObject.dialPrefix=s.getString(4);
						newObject.id=_tmpID;
						putToCache(newObject);
					}
					result.add(newObject);
				}
			}
			catch(Exception exc)
			{
				System.err.println(exc);
				exc.printStackTrace();
			}
			stmt.close();
		
		}
		catch (Exception ex)
		{
			System.err.println(ex);
			ex.printStackTrace();
		}
		return result;
	}

	/**
	 *  Method:      findByName(String _name)
	 *  Description: 
	 *  Returns:     ArrayList<City>
	 */
	public static ArrayList findByName(String _name)
	{
		ArrayList result = new ArrayList();
		SaveStatement  stmt;

		try
		{
			stmt  = ConnectionManager.getValid().createStatement("_dbCity.findByName");
			try
			{
				ResultSet s = stmt.executeQuery( "SELECT id, state_id, name, dialPrefix FROM City WHERE name='"+toSQL(_name)+"'"+" order by generatedId desc");
				while(s.next())
				{
					String _tmpID = s.getString(1);
					City newObject = (City)getFromCache(_tmpID);
					if(newObject ==null)
					{
						newObject = new City();
						newObject.state_id=s.getString(2);
						newObject.name=s.getString(3);
						newObject.dialPrefix=s.getString(4);
						newObject.id=_tmpID;
						putToCache(newObject);
					}
					result.add(newObject);
				}
			}
			catch(Exception exc)
			{
				System.err.println(exc);
				exc.printStackTrace();
			}
			stmt.close();
		
		}
		catch (Exception ex)
		{
			System.err.println(ex);
			ex.printStackTrace();
		}
		return result;
	}

	/**
	 *  Method:      findByDialPrefix(String _dialPrefix)
	 *  Description: 
	 *  Returns:     ArrayList<City>
	 */
	public static ArrayList findByDialPrefix(String _dialPrefix)
	{
		ArrayList result = new ArrayList();
		SaveStatement  stmt;

		try
		{
			stmt  = ConnectionManager.getValid().createStatement("_dbCity.findByDialPrefix");
			try
			{
				ResultSet s = stmt.executeQuery( "SELECT id, state_id, name, dialPrefix FROM City WHERE dialPrefix='"+toSQL(_dialPrefix)+"'"+" order by generatedId desc");
				while(s.next())
				{
					String _tmpID = s.getString(1);
					City newObject = (City)getFromCache(_tmpID);
					if(newObject ==null)
					{
						newObject = new City();
						newObject.state_id=s.getString(2);
						newObject.name=s.getString(3);
						newObject.dialPrefix=s.getString(4);
						newObject.id=_tmpID;
						putToCache(newObject);
					}
					result.add(newObject);
				}
			}
			catch(Exception exc)
			{
				System.err.println(exc);
				exc.printStackTrace();
			}
			stmt.close();
		
		}
		catch (Exception ex)
		{
			System.err.println(ex);
			ex.printStackTrace();
		}
		return result;
	}

	/**
	 *  Method:      findById(String _id)
	 *  Description: 
	 *  Returns:     City
	 */
	public static City findById(String _id)
	{
		City result = (City)getFromCache(_id);
		if(result!=null) return result;
		SaveStatement  stmt;

		try
		{
			stmt  = ConnectionManager.getValid().createStatement("_dbCity.findById");
			try
			{
				ResultSet s = stmt.executeQuery( "SELECT id, state_id, name, dialPrefix FROM City WHERE id='"+toSQL(_id)+"'"+" order by generatedId desc");
				if(s.next())
				{
					result = new City();
					result.state_id= s.getString(2);
					result.name= s.getString(3);
					result.dialPrefix= s.getString(4);
					result.id= _id;
					putToCache(result);
				}
			}
			catch(Exception exc)
			{
				System.err.println(exc);
				exc.printStackTrace();
			}
			stmt.close();
		
		}
		catch (Exception ex)
		{
			System.err.println(ex);
			ex.printStackTrace();
		}
		return result;
	}

	/**
	 * returns boolean
	 */
	public boolean commit()
	{
		SaveStatement  stmt;

		try
		{
			stmt  = ConnectionManager.getValid().createStatement("_dbCity.commit");
			try
			{
				stmt.executeUpdate( "UPDATE City set state_id= '"+toSQL(state_id)+"', name= '"+toSQL(name)+"', dialPrefix= '"+toSQL(dialPrefix)+"' WHERE id='"+id+"'");
			}
			catch(Exception exc)
			{
				System.err.println(exc);
				exc.printStackTrace();
			}
			stmt.close();
		
		}
		catch (Exception ex)
		{
			System.err.println(ex);
			ex.printStackTrace();
		}
		return true;
	}


	/**
	 * returns ArrayList<City>
	 */
	public static ArrayList getAll()
	{
		ArrayList result = new ArrayList();
		SaveStatement  stmt;

		try
		{
			stmt  = ConnectionManager.getValid().createStatement("_dbCity.getAll");
			try
			{
				ResultSet s = stmt.executeQuery( "SELECT id, state_id, name, dialPrefix FROM City order by generatedId desc");
				while(s.next())
				{
					String _tmpID = s.getString(1);
					City newObject = (City)getFromCache(_tmpID);
					if(newObject ==null)
					{
						newObject = new City();
						newObject.state_id=s.getString(2);
						newObject.name=s.getString(3);
						newObject.dialPrefix=s.getString(4);
						newObject.id=_tmpID;
						putToCache(newObject);
					}
					result.add(newObject);
				}
			}
			catch(Exception exc)
			{
				System.err.println(exc);
				exc.printStackTrace();
			}
			stmt.close();
		
		}
		catch (Exception ex)
		{
			System.err.println(ex);
			ex.printStackTrace();
		}
		return result;
	}


	/**
	 * create a new object in the database
	 */
	static public City createInstance( _dbState _state, String  _name, String  _dialPrefix )
	{
		City result = null;
		SaveStatement  stmt;

		try
		{
			stmt  = ConnectionManager.getValid().createStatement("_dbCity.createInstance");
			try
			{
				String nextGUID = new java.rmi.server.UID().toString();
				stmt.executeUpdate( "INSERT INTO City ( state_id, name, dialPrefix, id) VALUES ( '"+((_state==null)?"":_state.getId())+"',  '"+toSQL(_name)+"',  '"+toSQL(_dialPrefix)+"', '"+nextGUID+"')");
				result = new City();
				result.state_id= (_state==null)?"":_state.getId();
				result.name= _name;
				result.dialPrefix= _dialPrefix;
				result.id= nextGUID;
			}
			catch(Exception exc)
			{
				System.err.println(exc);
				exc.printStackTrace();
			}
			stmt.close();
		
		}
		catch (Exception ex)
		{
			System.err.println(ex);
			ex.printStackTrace();
		}
		return result;
	}


	/**
	 * create a new object in the database
	 */
	static public void newInstance( _dbState _state, String  _name, String  _dialPrefix )
	{
		SaveStatement  stmt;

		try
		{
			stmt  = ConnectionManager.getValid().createStatement("_dbCity.newInstance");
			try
			{
				String nextGUID = new java.rmi.server.UID().toString();
				stmt.executeUpdate( "INSERT INTO City ( state_id, name, dialPrefix, id) VALUES ( '"+((_state==null)?"":_state.getId())+"',  '"+toSQL(_name)+"',  '"+toSQL(_dialPrefix)+"', '"+nextGUID+"')");
			}
			catch(Exception exc)
			{
				System.err.println(exc);
				exc.printStackTrace();
			}
			stmt.close();
		
		}
		catch (Exception ex)
		{
			System.err.println(ex);
			ex.printStackTrace();
		}
	}


	/**
	 * destroy a object in the database
	 */
	static public boolean destroyInstance( String  _key)
	{
		boolean result = false;
		SaveStatement  stmt;

		try
		{
			stmt  = ConnectionManager.getValid().createStatement("_dbCity.destroyInstance");
			try
			{
					stmt.executeUpdate( "DELETE FROM City WHERE id='"+_key+"'");
					result = true;
			}
			catch(Exception exc)
			{
				System.err.println(exc);
				exc.printStackTrace();
			}
			stmt.close();
		
		}
		catch (Exception ex)
		{
			System.err.println(ex);
			ex.printStackTrace();
		}
		return result;
	}


	/**
	 * destroy ALL objects in the database
	 */
	static public boolean destroyAll()
	{
		boolean result = false;
		SaveStatement  stmt;

		try
		{
			stmt  = ConnectionManager.getValid().createStatement("_dbCity.destroyAll");
			try
			{
					stmt.executeUpdate("DELETE from City" );
					result = true;
			}
			catch(Exception exc)
			{
				System.err.println(exc);
				exc.printStackTrace();
			}
			stmt.close();
		
		}
		catch (Exception ex)
		{
			System.err.println(ex);
			ex.printStackTrace();
		}
		return result;
	}


	/**
	 */
	public String toString()
	{
		StringBuffer result = new StringBuffer(1024);
		result.append(state_id);
		result.append("|");
		result.append(name);
		result.append("|");
		result.append(dialPrefix);
		result.append("|");
		result.append(id);
		return result.toString();
	}


	/**
	 * init the class
	 */
	static
	{
		try
		{
			DatabaseMetaData dMeta = ConnectionManager.getValid().getMetaData ();
			ResultSet result;
			result=dMeta.getColumns(null,null,"City","state_id");
			if(!result.next())
			{
				System.out.println("ERROR: installed DB-schema not compatible to java classes");
				System.out.println("       Attribute 'state_id' in table 'City' missing");
			}
			result.close();
			result=dMeta.getColumns(null,null,"City","name");
			if(!result.next())
			{
				System.out.println("ERROR: installed DB-schema not compatible to java classes");
				System.out.println("       Attribute 'name' in table 'City' missing");
			}
			result.close();
			result=dMeta.getColumns(null,null,"City","dialPrefix");
			if(!result.next())
			{
				System.out.println("ERROR: installed DB-schema not compatible to java classes");
				System.out.println("       Attribute 'dialPrefix' in table 'City' missing");
			}
			result.close();
			result=dMeta.getColumns(null,null,"City","id");
			if(!result.next())
			{
				System.out.println("ERROR: installed DB-schema not compatible to java classes");
				System.out.println("       Attribute 'id' in table 'City' missing");
			}
			result.close();
		}
		catch (Exception ex)
		{
		}
	}


}
