package de.shorti.baseknowledge.objects;

/**
 * Class generated by automatic ClassGenerator
 * Date: Sat May 11 21:15:22 GMT+02:00 2002
 */
import de.shorti.db.*;
import java.util.ArrayList;
import java.util.Iterator;
import java.sql.*;

class _dbRadioStation extends dbObject 
{

	String    name;
	String    description;
	String    geschaeftsstelle_id;	// Foreign Key pointing to Table [Geschaeftsstelle], Field [id]


	/**
	 * destroy a object in the database
	 */
	public boolean destroy()
	{
		boolean result = false;
		String    _key   = id;
		SaveStatement  stmt;

		try
		{
			stmt  = ConnectionManager.getValid().createStatement("_dbRadioStation.destroyInstance");
			try
			{
					stmt.executeUpdate( "DELETE FROM RadioStation WHERE id='"+_key+"'");
					result = true;
					removeFromCache(this);
					id     = null;
			}
			catch(Exception exc)
			{
				System.err.println(exc);
				exc.printStackTrace();
			}
			stmt.close();
		
		}
		catch (Exception ex)
		{
			System.err.println(ex);
			ex.printStackTrace();
		}
		return result;
	}



	/**
	 * Method:      getName()
	 * Description: 
	 * Returns:     String
	 */
	public String getName()
	{
		return name;
	}

	/**
	 * Method:      setName(String _name, boolean _autoCommit)
	 * Description: 
	 * Returns:     void
	 */
	public void setName(String _name, boolean _autoCommit)
	{
		name=_name;
		if(_autoCommit)
		{
			commit();
		}
	}

	/**
	 * Method:      getDescription()
	 * Description: 
	 * Returns:     String
	 */
	public String getDescription()
	{
		return description;
	}

	/**
	 * Method:      setDescription(String _description, boolean _autoCommit)
	 * Description: 
	 * Returns:     void
	 */
	public void setDescription(String _description, boolean _autoCommit)
	{
		description=_description;
		if(_autoCommit)
		{
			commit();
		}
	}

	/**
	 * Method:      getId()
	 * Description: 
	 * Returns:     String
	 */
	public String getId()
	{
		return id;
	}

	/**
	 * Method:      getGeschaeftsstelle()
	 * Description: 
	 * Returns:     Geschaeftsstelle
	 */
	public Geschaeftsstelle getGeschaeftsstelle()
	{
		return Geschaeftsstelle.findById(geschaeftsstelle_id);
	}

	/**
	 * Method:      setGeschaeftsstelle()
	 * Description: 
	 * Returns:     void
	 */
	public void setGeschaeftsstelle(Geschaeftsstelle _foreigner, boolean _autocommit)
	{
		geschaeftsstelle_id= _foreigner.getId();
		if (_autocommit == true)
			commit();
	}

	/**
	 *  Method:      getPlayListEntries()
	 *  Description:                              
	 *  Returns:     ArrayList<PlayListEntry>
	 */
	public ArrayList getPlayListEntries()
	{
		return _dbPlayListEntry.findByRadioStation(this);
	}


	/**
	 *  Method:      getRadioRelayStations()
	 *  Description:                              
	 *  Returns:     ArrayList<RadioRelayStation>
	 */
	public ArrayList getRadioRelayStations()
	{
		return _dbRadioRelayStation.findByRadioStation(this);
	}


	/**
	 *  Method:      findByName(String _name)
	 *  Description: 
	 *  Returns:     RadioStation
	 */
	public static RadioStation findByName(String _name)
	{
		RadioStation result = null;
		SaveStatement  stmt;

		try
		{
			stmt  = ConnectionManager.getValid().createStatement("_dbRadioStation.findByName");
			try
			{
				ResultSet s = stmt.executeQuery( "SELECT id, name, description, geschaeftsstelle_id FROM RadioStation WHERE name='"+toSQL(_name)+"'"+" order by generatedId desc");
				if(s.next())
				{
					String _tmpID = s.getString(1);
					result = (RadioStation)getFromCache(_tmpID);
					if(result ==null)
					{
						result = new RadioStation();
						result.name= s.getString(2);
						result.description= s.getString(3);
						result.geschaeftsstelle_id= s.getString(4);
						result.id= _tmpID;
						putToCache(result);
					}
				}
			}
			catch(Exception exc)
			{
				System.err.println(exc);
				exc.printStackTrace();
			}
			stmt.close();
		
		}
		catch (Exception ex)
		{
			System.err.println(ex);
			ex.printStackTrace();
		}
		return result;
	}

	/**
	 *  Method:      findByDescription(String _description)
	 *  Description: 
	 *  Returns:     ArrayList<RadioStation>
	 */
	public static ArrayList findByDescription(String _description)
	{
		ArrayList result = new ArrayList();
		SaveStatement  stmt;

		try
		{
			stmt  = ConnectionManager.getValid().createStatement("_dbRadioStation.findByDescription");
			try
			{
				ResultSet s = stmt.executeQuery( "SELECT id, name, description, geschaeftsstelle_id FROM RadioStation WHERE description='"+toSQL(_description)+"'"+" order by generatedId desc");
				while(s.next())
				{
					String _tmpID = s.getString(1);
					RadioStation newObject = (RadioStation)getFromCache(_tmpID);
					if(newObject ==null)
					{
						newObject = new RadioStation();
						newObject.name=s.getString(2);
						newObject.description=s.getString(3);
						newObject.geschaeftsstelle_id=s.getString(4);
						newObject.id=_tmpID;
						putToCache(newObject);
					}
					result.add(newObject);
				}
			}
			catch(Exception exc)
			{
				System.err.println(exc);
				exc.printStackTrace();
			}
			stmt.close();
		
		}
		catch (Exception ex)
		{
			System.err.println(ex);
			ex.printStackTrace();
		}
		return result;
	}

	/**
	 *  Method:      findByGeschaeftsstelle(_dbGeschaeftsstelle _geschaeftsstelle)
	 *  Description: 
	 *  Returns:     ArrayList<RadioStation>
	 */
	public static ArrayList findByGeschaeftsstelle(_dbGeschaeftsstelle _geschaeftsstelle)
	{
		ArrayList result = new ArrayList();
		SaveStatement  stmt;

		try
		{
			stmt  = ConnectionManager.getValid().createStatement("_dbRadioStation.findByGeschaeftsstelle");
			try
			{
				ResultSet s = stmt.executeQuery( "SELECT id, name, description, geschaeftsstelle_id FROM RadioStation WHERE geschaeftsstelle_id='"+toSQL(((_geschaeftsstelle==null)?"":_geschaeftsstelle.getId()))+"'"+" order by generatedId desc");
				while(s.next())
				{
					String _tmpID = s.getString(1);
					RadioStation newObject = (RadioStation)getFromCache(_tmpID);
					if(newObject ==null)
					{
						newObject = new RadioStation();
						newObject.name=s.getString(2);
						newObject.description=s.getString(3);
						newObject.geschaeftsstelle_id=s.getString(4);
						newObject.id=_tmpID;
						putToCache(newObject);
					}
					result.add(newObject);
				}
			}
			catch(Exception exc)
			{
				System.err.println(exc);
				exc.printStackTrace();
			}
			stmt.close();
		
		}
		catch (Exception ex)
		{
			System.err.println(ex);
			ex.printStackTrace();
		}
		return result;
	}

	/**
	 *  Method:      findById(String _id)
	 *  Description: 
	 *  Returns:     RadioStation
	 */
	public static RadioStation findById(String _id)
	{
		RadioStation result = (RadioStation)getFromCache(_id);
		if(result!=null) return result;
		SaveStatement  stmt;

		try
		{
			stmt  = ConnectionManager.getValid().createStatement("_dbRadioStation.findById");
			try
			{
				ResultSet s = stmt.executeQuery( "SELECT id, name, description, geschaeftsstelle_id FROM RadioStation WHERE id='"+toSQL(_id)+"'"+" order by generatedId desc");
				if(s.next())
				{
					result = new RadioStation();
					result.name= s.getString(2);
					result.description= s.getString(3);
					result.geschaeftsstelle_id= s.getString(4);
					result.id= _id;
					putToCache(result);
				}
			}
			catch(Exception exc)
			{
				System.err.println(exc);
				exc.printStackTrace();
			}
			stmt.close();
		
		}
		catch (Exception ex)
		{
			System.err.println(ex);
			ex.printStackTrace();
		}
		return result;
	}

	/**
	 * returns boolean
	 */
	public boolean commit()
	{
		SaveStatement  stmt;

		try
		{
			stmt  = ConnectionManager.getValid().createStatement("_dbRadioStation.commit");
			try
			{
				stmt.executeUpdate( "UPDATE RadioStation set name= '"+toSQL(name)+"', description= '"+toSQL(description)+"', geschaeftsstelle_id= '"+toSQL(geschaeftsstelle_id)+"' WHERE id='"+id+"'");
			}
			catch(Exception exc)
			{
				System.err.println(exc);
				exc.printStackTrace();
			}
			stmt.close();
		
		}
		catch (Exception ex)
		{
			System.err.println(ex);
			ex.printStackTrace();
		}
		return true;
	}


	/**
	 * returns ArrayList<RadioStation>
	 */
	public static ArrayList getAll()
	{
		ArrayList result = new ArrayList();
		SaveStatement  stmt;

		try
		{
			stmt  = ConnectionManager.getValid().createStatement("_dbRadioStation.getAll");
			try
			{
				ResultSet s = stmt.executeQuery( "SELECT id, name, description, geschaeftsstelle_id FROM RadioStation order by generatedId desc");
				while(s.next())
				{
					String _tmpID = s.getString(1);
					RadioStation newObject = (RadioStation)getFromCache(_tmpID);
					if(newObject ==null)
					{
						newObject = new RadioStation();
						newObject.name=s.getString(2);
						newObject.description=s.getString(3);
						newObject.geschaeftsstelle_id=s.getString(4);
						newObject.id=_tmpID;
						putToCache(newObject);
					}
					result.add(newObject);
				}
			}
			catch(Exception exc)
			{
				System.err.println(exc);
				exc.printStackTrace();
			}
			stmt.close();
		
		}
		catch (Exception ex)
		{
			System.err.println(ex);
			ex.printStackTrace();
		}
		return result;
	}


	/**
	 * create a new object in the database
	 */
	static public RadioStation createInstance( String  _name, String  _description, _dbGeschaeftsstelle _geschaeftsstelle )
	{
		RadioStation result = null;
		SaveStatement  stmt;

		try
		{
			stmt  = ConnectionManager.getValid().createStatement("_dbRadioStation.createInstance");
			try
			{
				String nextGUID = new java.rmi.server.UID().toString();
				stmt.executeUpdate( "INSERT INTO RadioStation ( name, description, geschaeftsstelle_id, id) VALUES ( '"+toSQL(_name)+"',  '"+toSQL(_description)+"',  '"+((_geschaeftsstelle==null)?"":_geschaeftsstelle.getId())+"', '"+nextGUID+"')");
				result = new RadioStation();
				result.name= _name;
				result.description= _description;
				result.geschaeftsstelle_id= (_geschaeftsstelle==null)?"":_geschaeftsstelle.getId();
				result.id= nextGUID;
			}
			catch(Exception exc)
			{
				System.err.println(exc);
				exc.printStackTrace();
			}
			stmt.close();
		
		}
		catch (Exception ex)
		{
			System.err.println(ex);
			ex.printStackTrace();
		}
		return result;
	}


	/**
	 * create a new object in the database
	 */
	static public void newInstance( String  _name, String  _description, _dbGeschaeftsstelle _geschaeftsstelle )
	{
		SaveStatement  stmt;

		try
		{
			stmt  = ConnectionManager.getValid().createStatement("_dbRadioStation.newInstance");
			try
			{
				String nextGUID = new java.rmi.server.UID().toString();
				stmt.executeUpdate( "INSERT INTO RadioStation ( name, description, geschaeftsstelle_id, id) VALUES ( '"+toSQL(_name)+"',  '"+toSQL(_description)+"',  '"+((_geschaeftsstelle==null)?"":_geschaeftsstelle.getId())+"', '"+nextGUID+"')");
			}
			catch(Exception exc)
			{
				System.err.println(exc);
				exc.printStackTrace();
			}
			stmt.close();
		
		}
		catch (Exception ex)
		{
			System.err.println(ex);
			ex.printStackTrace();
		}
	}


	/**
	 * destroy a object in the database
	 */
	static public boolean destroyInstance( String  _key)
	{
		boolean result = false;
		SaveStatement  stmt;

		try
		{
			stmt  = ConnectionManager.getValid().createStatement("_dbRadioStation.destroyInstance");
			try
			{
					stmt.executeUpdate( "DELETE FROM RadioStation WHERE id='"+_key+"'");
					result = true;
			}
			catch(Exception exc)
			{
				System.err.println(exc);
				exc.printStackTrace();
			}
			stmt.close();
		
		}
		catch (Exception ex)
		{
			System.err.println(ex);
			ex.printStackTrace();
		}
		return result;
	}


	/**
	 * destroy ALL objects in the database
	 */
	static public boolean destroyAll()
	{
		boolean result = false;
		SaveStatement  stmt;

		try
		{
			stmt  = ConnectionManager.getValid().createStatement("_dbRadioStation.destroyAll");
			try
			{
					stmt.executeUpdate("DELETE from RadioStation" );
					result = true;
			}
			catch(Exception exc)
			{
				System.err.println(exc);
				exc.printStackTrace();
			}
			stmt.close();
		
		}
		catch (Exception ex)
		{
			System.err.println(ex);
			ex.printStackTrace();
		}
		return result;
	}


	/**
	 */
	public String toString()
	{
		StringBuffer result = new StringBuffer(1024);
		result.append(name);
		result.append("|");
		result.append(description);
		result.append("|");
		result.append(geschaeftsstelle_id);
		result.append("|");
		result.append(id);
		return result.toString();
	}


	/**
	 * init the class
	 */
	static
	{
		try
		{
			DatabaseMetaData dMeta = ConnectionManager.getValid().getMetaData ();
			ResultSet result;
			result=dMeta.getColumns(null,null,"RadioStation","name");
			if(!result.next())
			{
				System.out.println("ERROR: installed DB-schema not compatible to java classes");
				System.out.println("       Attribute 'name' in table 'RadioStation' missing");
			}
			result.close();
			result=dMeta.getColumns(null,null,"RadioStation","description");
			if(!result.next())
			{
				System.out.println("ERROR: installed DB-schema not compatible to java classes");
				System.out.println("       Attribute 'description' in table 'RadioStation' missing");
			}
			result.close();
			result=dMeta.getColumns(null,null,"RadioStation","geschaeftsstelle_id");
			if(!result.next())
			{
				System.out.println("ERROR: installed DB-schema not compatible to java classes");
				System.out.println("       Attribute 'geschaeftsstelle_id' in table 'RadioStation' missing");
			}
			result.close();
			result=dMeta.getColumns(null,null,"RadioStation","id");
			if(!result.next())
			{
				System.out.println("ERROR: installed DB-schema not compatible to java classes");
				System.out.println("       Attribute 'id' in table 'RadioStation' missing");
			}
			result.close();
		}
		catch (Exception ex)
		{
		}
	}


}
