package de.shorti.baseknowledge.objects;

/**
 * Class generated by automatic ClassGenerator
 * Date: Sat May 11 21:15:22 GMT+02:00 2002
 */
import java.sql.DatabaseMetaData;
import java.sql.ResultSet;
import java.util.ArrayList;

class _dbRadioRelayStation extends dbObject 
{

	String    zipCode_id;	// Foreign Key pointing to Table [ZipCode], Field [id]
	String    radioStation_id;	// Foreign Key pointing to Table [RadioStation], Field [id]
	String    frequenz;


	/**
	 * destroy a object in the database
	 */
	public boolean destroy()
	{
		boolean result = false;
		String    _key   = id;
		SaveStatement  stmt;

		try
		{
			stmt  = ConnectionManager.getValid().createStatement("_dbRadioRelayStation.destroyInstance");
			try
			{
					stmt.executeUpdate( "DELETE FROM RadioRelayStation WHERE id='"+_key+"'");
					result = true;
					removeFromCache(this);
					id     = null;
			}
			catch(Exception exc)
			{
				System.err.println(exc);
				exc.printStackTrace();
			}
			stmt.close();
		
		}
		catch (Exception ex)
		{
			System.err.println(ex);
			ex.printStackTrace();
		}
		return result;
	}



	/**
	 * Method:      getFrequenz()
	 * Description: 
	 * Returns:     String
	 */
	public String getFrequenz()
	{
		return frequenz;
	}

	/**
	 * Method:      setFrequenz(String _frequenz, boolean _autoCommit)
	 * Description: 
	 * Returns:     void
	 */
	public void setFrequenz(String _frequenz, boolean _autoCommit)
	{
		frequenz=_frequenz;
		if(_autoCommit)
		{
			commit();
		}
	}

	/**
	 * Method:      getId()
	 * Description: 
	 * Returns:     String
	 */
	public String getId()
	{
		return id;
	}

	/**
	 * Method:      getZipCode()
	 * Description: 
	 * Returns:     ZipCode
	 */
	public ZipCode getZipCode()
	{
		return ZipCode.findById(zipCode_id);
	}

	/**
	 * Method:      setZipCode()
	 * Description: 
	 * Returns:     void
	 */
	public void setZipCode(ZipCode _foreigner, boolean _autocommit)
	{
		zipCode_id= _foreigner.getId();
		if (_autocommit == true)
			commit();
	}

	/**
	 * Method:      getRadioStation()
	 * Description: 
	 * Returns:     RadioStation
	 */
	public RadioStation getRadioStation()
	{
		return RadioStation.findById(radioStation_id);
	}

	/**
	 * Method:      setRadioStation()
	 * Description: 
	 * Returns:     void
	 */
	public void setRadioStation(RadioStation _foreigner, boolean _autocommit)
	{
		radioStation_id= _foreigner.getId();
		if (_autocommit == true)
			commit();
	}

	/**
	 *  Method:      findByZipCode(_dbZipCode _zipCode)
	 *  Description: 
	 *  Returns:     ArrayList<RadioRelayStation>
	 */
	public static ArrayList findByZipCode(_dbZipCode _zipCode)
	{
		ArrayList result = new ArrayList();
		SaveStatement  stmt;

		try
		{
			stmt  = ConnectionManager.getValid().createStatement("_dbRadioRelayStation.findByZipCode");
			try
			{
				ResultSet s = stmt.executeQuery( "SELECT id, zipCode_id, radioStation_id, frequenz FROM RadioRelayStation WHERE zipCode_id='"+toSQL(((_zipCode==null)?"":_zipCode.getId()))+"'"+" order by generatedId desc");
				while(s.next())
				{
					String _tmpID = s.getString(1);
					RadioRelayStation newObject = (RadioRelayStation)getFromCache(_tmpID);
					if(newObject ==null)
					{
						newObject = new RadioRelayStation();
						newObject.zipCode_id=s.getString(2);
						newObject.radioStation_id=s.getString(3);
						newObject.frequenz=s.getString(4);
						newObject.id=_tmpID;
						putToCache(newObject);
					}
					result.add(newObject);
				}
			}
			catch(Exception exc)
			{
				System.err.println(exc);
				exc.printStackTrace();
			}
			stmt.close();
		
		}
		catch (Exception ex)
		{
			System.err.println(ex);
			ex.printStackTrace();
		}
		return result;
	}

	/**
	 *  Method:      findByRadioStation(_dbRadioStation _radioStation)
	 *  Description: 
	 *  Returns:     ArrayList<RadioRelayStation>
	 */
	public static ArrayList findByRadioStation(_dbRadioStation _radioStation)
	{
		ArrayList result = new ArrayList();
		SaveStatement  stmt;

		try
		{
			stmt  = ConnectionManager.getValid().createStatement("_dbRadioRelayStation.findByRadioStation");
			try
			{
				ResultSet s = stmt.executeQuery( "SELECT id, zipCode_id, radioStation_id, frequenz FROM RadioRelayStation WHERE radioStation_id='"+toSQL(((_radioStation==null)?"":_radioStation.getId()))+"'"+" order by generatedId desc");
				while(s.next())
				{
					String _tmpID = s.getString(1);
					RadioRelayStation newObject = (RadioRelayStation)getFromCache(_tmpID);
					if(newObject ==null)
					{
						newObject = new RadioRelayStation();
						newObject.zipCode_id=s.getString(2);
						newObject.radioStation_id=s.getString(3);
						newObject.frequenz=s.getString(4);
						newObject.id=_tmpID;
						putToCache(newObject);
					}
					result.add(newObject);
				}
			}
			catch(Exception exc)
			{
				System.err.println(exc);
				exc.printStackTrace();
			}
			stmt.close();
		
		}
		catch (Exception ex)
		{
			System.err.println(ex);
			ex.printStackTrace();
		}
		return result;
	}

	/**
	 *  Method:      findByFrequenz(String _frequenz)
	 *  Description: 
	 *  Returns:     ArrayList<RadioRelayStation>
	 */
	public static ArrayList findByFrequenz(String _frequenz)
	{
		ArrayList result = new ArrayList();
		SaveStatement  stmt;

		try
		{
			stmt  = ConnectionManager.getValid().createStatement("_dbRadioRelayStation.findByFrequenz");
			try
			{
				ResultSet s = stmt.executeQuery( "SELECT id, zipCode_id, radioStation_id, frequenz FROM RadioRelayStation WHERE frequenz='"+toSQL(_frequenz)+"'"+" order by generatedId desc");
				while(s.next())
				{
					String _tmpID = s.getString(1);
					RadioRelayStation newObject = (RadioRelayStation)getFromCache(_tmpID);
					if(newObject ==null)
					{
						newObject = new RadioRelayStation();
						newObject.zipCode_id=s.getString(2);
						newObject.radioStation_id=s.getString(3);
						newObject.frequenz=s.getString(4);
						newObject.id=_tmpID;
						putToCache(newObject);
					}
					result.add(newObject);
				}
			}
			catch(Exception exc)
			{
				System.err.println(exc);
				exc.printStackTrace();
			}
			stmt.close();
		
		}
		catch (Exception ex)
		{
			System.err.println(ex);
			ex.printStackTrace();
		}
		return result;
	}

	/**
	 *  Method:      findById(String _id)
	 *  Description: 
	 *  Returns:     RadioRelayStation
	 */
	public static RadioRelayStation findById(String _id)
	{
		RadioRelayStation result = (RadioRelayStation)getFromCache(_id);
		if(result!=null) return result;
		SaveStatement  stmt;

		try
		{
			stmt  = ConnectionManager.getValid().createStatement("_dbRadioRelayStation.findById");
			try
			{
				ResultSet s = stmt.executeQuery( "SELECT id, zipCode_id, radioStation_id, frequenz FROM RadioRelayStation WHERE id='"+toSQL(_id)+"'"+" order by generatedId desc");
				if(s.next())
				{
					result = new RadioRelayStation();
					result.zipCode_id= s.getString(2);
					result.radioStation_id= s.getString(3);
					result.frequenz= s.getString(4);
					result.id= _id;
					putToCache(result);
				}
			}
			catch(Exception exc)
			{
				System.err.println(exc);
				exc.printStackTrace();
			}
			stmt.close();
		
		}
		catch (Exception ex)
		{
			System.err.println(ex);
			ex.printStackTrace();
		}
		return result;
	}

	/**
	 * returns boolean
	 */
	public boolean commit()
	{
		SaveStatement  stmt;

		try
		{
			stmt  = ConnectionManager.getValid().createStatement("_dbRadioRelayStation.commit");
			try
			{
				stmt.executeUpdate( "UPDATE RadioRelayStation set zipCode_id= '"+toSQL(zipCode_id)+"', radioStation_id= '"+toSQL(radioStation_id)+"', frequenz= '"+toSQL(frequenz)+"' WHERE id='"+id+"'");
			}
			catch(Exception exc)
			{
				System.err.println(exc);
				exc.printStackTrace();
			}
			stmt.close();
		
		}
		catch (Exception ex)
		{
			System.err.println(ex);
			ex.printStackTrace();
		}
		return true;
	}


	/**
	 * returns ArrayList<RadioRelayStation>
	 */
	public static ArrayList getAll()
	{
		ArrayList result = new ArrayList();
		SaveStatement  stmt;

		try
		{
			stmt  = ConnectionManager.getValid().createStatement("_dbRadioRelayStation.getAll");
			try
			{
				ResultSet s = stmt.executeQuery( "SELECT id, zipCode_id, radioStation_id, frequenz FROM RadioRelayStation order by generatedId desc");
				while(s.next())
				{
					String _tmpID = s.getString(1);
					RadioRelayStation newObject = (RadioRelayStation)getFromCache(_tmpID);
					if(newObject ==null)
					{
						newObject = new RadioRelayStation();
						newObject.zipCode_id=s.getString(2);
						newObject.radioStation_id=s.getString(3);
						newObject.frequenz=s.getString(4);
						newObject.id=_tmpID;
						putToCache(newObject);
					}
					result.add(newObject);
				}
			}
			catch(Exception exc)
			{
				System.err.println(exc);
				exc.printStackTrace();
			}
			stmt.close();
		
		}
		catch (Exception ex)
		{
			System.err.println(ex);
			ex.printStackTrace();
		}
		return result;
	}


	/**
	 * create a new object in the database
	 */
	static public RadioRelayStation createInstance( _dbZipCode _zipCode, _dbRadioStation _radioStation, String  _frequenz )
	{
		RadioRelayStation result = null;
		SaveStatement  stmt;

		try
		{
			stmt  = ConnectionManager.getValid().createStatement("_dbRadioRelayStation.createInstance");
			try
			{
				String nextGUID = new java.rmi.server.UID().toString();
				stmt.executeUpdate( "INSERT INTO RadioRelayStation ( zipCode_id, radioStation_id, frequenz, id) VALUES ( '"+((_zipCode==null)?"":_zipCode.getId())+"',  '"+((_radioStation==null)?"":_radioStation.getId())+"',  '"+toSQL(_frequenz)+"', '"+nextGUID+"')");
				result = new RadioRelayStation();
				result.zipCode_id= (_zipCode==null)?"":_zipCode.getId();
				result.radioStation_id= (_radioStation==null)?"":_radioStation.getId();
				result.frequenz= _frequenz;
				result.id= nextGUID;
			}
			catch(Exception exc)
			{
				System.err.println(exc);
				exc.printStackTrace();
			}
			stmt.close();
		
		}
		catch (Exception ex)
		{
			System.err.println(ex);
			ex.printStackTrace();
		}
		return result;
	}


	/**
	 * create a new object in the database
	 */
	static public void newInstance( _dbZipCode _zipCode, _dbRadioStation _radioStation, String  _frequenz )
	{
		SaveStatement  stmt;

		try
		{
			stmt  = ConnectionManager.getValid().createStatement("_dbRadioRelayStation.newInstance");
			try
			{
				String nextGUID = new java.rmi.server.UID().toString();
				stmt.executeUpdate( "INSERT INTO RadioRelayStation ( zipCode_id, radioStation_id, frequenz, id) VALUES ( '"+((_zipCode==null)?"":_zipCode.getId())+"',  '"+((_radioStation==null)?"":_radioStation.getId())+"',  '"+toSQL(_frequenz)+"', '"+nextGUID+"')");
			}
			catch(Exception exc)
			{
				System.err.println(exc);
				exc.printStackTrace();
			}
			stmt.close();
		
		}
		catch (Exception ex)
		{
			System.err.println(ex);
			ex.printStackTrace();
		}
	}


	/**
	 * destroy a object in the database
	 */
	static public boolean destroyInstance( String  _key)
	{
		boolean result = false;
		SaveStatement  stmt;

		try
		{
			stmt  = ConnectionManager.getValid().createStatement("_dbRadioRelayStation.destroyInstance");
			try
			{
					stmt.executeUpdate( "DELETE FROM RadioRelayStation WHERE id='"+_key+"'");
					result = true;
			}
			catch(Exception exc)
			{
				System.err.println(exc);
				exc.printStackTrace();
			}
			stmt.close();
		
		}
		catch (Exception ex)
		{
			System.err.println(ex);
			ex.printStackTrace();
		}
		return result;
	}


	/**
	 * destroy ALL objects in the database
	 */
	static public boolean destroyAll()
	{
		boolean result = false;
		SaveStatement  stmt;

		try
		{
			stmt  = ConnectionManager.getValid().createStatement("_dbRadioRelayStation.destroyAll");
			try
			{
					stmt.executeUpdate("DELETE from RadioRelayStation" );
					result = true;
			}
			catch(Exception exc)
			{
				System.err.println(exc);
				exc.printStackTrace();
			}
			stmt.close();
		
		}
		catch (Exception ex)
		{
			System.err.println(ex);
			ex.printStackTrace();
		}
		return result;
	}


	/**
	 */
	public String toString()
	{
		StringBuffer result = new StringBuffer(1024);
		result.append(zipCode_id);
		result.append("|");
		result.append(radioStation_id);
		result.append("|");
		result.append(frequenz);
		result.append("|");
		result.append(id);
		return result.toString();
	}


	/**
	 * init the class
	 */
	static
	{
		try
		{
			DatabaseMetaData dMeta = ConnectionManager.getValid().getMetaData ();
			ResultSet result;
			result=dMeta.getColumns(null,null,"RadioRelayStation","zipCode_id");
			if(!result.next())
			{
				System.out.println("ERROR: installed DB-schema not compatible to java classes");
				System.out.println("       Attribute 'zipCode_id' in table 'RadioRelayStation' missing");
			}
			result.close();
			result=dMeta.getColumns(null,null,"RadioRelayStation","radioStation_id");
			if(!result.next())
			{
				System.out.println("ERROR: installed DB-schema not compatible to java classes");
				System.out.println("       Attribute 'radioStation_id' in table 'RadioRelayStation' missing");
			}
			result.close();
			result=dMeta.getColumns(null,null,"RadioRelayStation","frequenz");
			if(!result.next())
			{
				System.out.println("ERROR: installed DB-schema not compatible to java classes");
				System.out.println("       Attribute 'frequenz' in table 'RadioRelayStation' missing");
			}
			result.close();
			result=dMeta.getColumns(null,null,"RadioRelayStation","id");
			if(!result.next())
			{
				System.out.println("ERROR: installed DB-schema not compatible to java classes");
				System.out.println("       Attribute 'id' in table 'RadioRelayStation' missing");
			}
			result.close();
		}
		catch (Exception ex)
		{
		}
	}


}
