package de.shorti.baseknowledge.objects;

/**
 * Class generated by automatic ClassGenerator
 * Date: Sat May 11 21:15:23 GMT+02:00 2002
 */
import java.sql.DatabaseMetaData;
import java.sql.ResultSet;
import java.util.ArrayList;

class _dbSystemConfiguration extends dbObject 
{

	String    name;
	String    value;


	/**
	 * destroy a object in the database
	 */
	public boolean destroy()
	{
		boolean result = false;
		String    _key   = id;
		SaveStatement  stmt;

		try
		{
			stmt  = ConnectionManager.getValid().createStatement("_dbSystemConfiguration.destroyInstance");
			try
			{
					stmt.executeUpdate( "DELETE FROM SystemConfiguration WHERE id='"+_key+"'");
					result = true;
					removeFromCache(this);
					id     = null;
			}
			catch(Exception exc)
			{
				System.err.println(exc);
				exc.printStackTrace();
			}
			stmt.close();
		
		}
		catch (Exception ex)
		{
			System.err.println(ex);
			ex.printStackTrace();
		}
		return result;
	}



	/**
	 * Method:      getName()
	 * Description: 
	 * Returns:     String
	 */
	public String getName()
	{
		return name;
	}

	/**
	 * Method:      setName(String _name, boolean _autoCommit)
	 * Description: 
	 * Returns:     void
	 */
	public void setName(String _name, boolean _autoCommit)
	{
		name=_name;
		if(_autoCommit)
		{
			commit();
		}
	}

	/**
	 * Method:      getValue()
	 * Description: 
	 * Returns:     String
	 */
	public String getValue()
	{
		return value;
	}

	/**
	 * Method:      setValue(String _value, boolean _autoCommit)
	 * Description: 
	 * Returns:     void
	 */
	public void setValue(String _value, boolean _autoCommit)
	{
		value=_value;
		if(_autoCommit)
		{
			commit();
		}
	}

	/**
	 * Method:      getId()
	 * Description: 
	 * Returns:     String
	 */
	public String getId()
	{
		return id;
	}

	/**
	 *  Method:      findByName(String _name)
	 *  Description: 
	 *  Returns:     SystemConfiguration
	 */
	public static SystemConfiguration findByName(String _name)
	{
		SystemConfiguration result = null;
		SaveStatement  stmt;

		try
		{
			stmt  = ConnectionManager.getValid().createStatement("_dbSystemConfiguration.findByName");
			try
			{
				ResultSet s = stmt.executeQuery( "SELECT id, name, value FROM SystemConfiguration WHERE name='"+toSQL(_name)+"'"+" order by generatedId desc");
				if(s.next())
				{
					String _tmpID = s.getString(1);
					result = (SystemConfiguration)getFromCache(_tmpID);
					if(result ==null)
					{
						result = new SystemConfiguration();
						result.name= s.getString(2);
						result.value= s.getString(3);
						result.id= _tmpID;
						putToCache(result);
					}
				}
			}
			catch(Exception exc)
			{
				System.err.println(exc);
				exc.printStackTrace();
			}
			stmt.close();
		
		}
		catch (Exception ex)
		{
			System.err.println(ex);
			ex.printStackTrace();
		}
		return result;
	}

	/**
	 *  Method:      findByValue(String _value)
	 *  Description: 
	 *  Returns:     ArrayList<SystemConfiguration>
	 */
	public static ArrayList findByValue(String _value)
	{
		ArrayList result = new ArrayList();
		SaveStatement  stmt;

		try
		{
			stmt  = ConnectionManager.getValid().createStatement("_dbSystemConfiguration.findByValue");
			try
			{
				ResultSet s = stmt.executeQuery( "SELECT id, name, value FROM SystemConfiguration WHERE value='"+toSQL(_value)+"'"+" order by generatedId desc");
				while(s.next())
				{
					String _tmpID = s.getString(1);
					SystemConfiguration newObject = (SystemConfiguration)getFromCache(_tmpID);
					if(newObject ==null)
					{
						newObject = new SystemConfiguration();
						newObject.name=s.getString(2);
						newObject.value=s.getString(3);
						newObject.id=_tmpID;
						putToCache(newObject);
					}
					result.add(newObject);
				}
			}
			catch(Exception exc)
			{
				System.err.println(exc);
				exc.printStackTrace();
			}
			stmt.close();
		
		}
		catch (Exception ex)
		{
			System.err.println(ex);
			ex.printStackTrace();
		}
		return result;
	}

	/**
	 *  Method:      findById(String _id)
	 *  Description: 
	 *  Returns:     SystemConfiguration
	 */
	public static SystemConfiguration findById(String _id)
	{
		SystemConfiguration result = (SystemConfiguration)getFromCache(_id);
		if(result!=null) return result;
		SaveStatement  stmt;

		try
		{
			stmt  = ConnectionManager.getValid().createStatement("_dbSystemConfiguration.findById");
			try
			{
				ResultSet s = stmt.executeQuery( "SELECT id, name, value FROM SystemConfiguration WHERE id='"+toSQL(_id)+"'"+" order by generatedId desc");
				if(s.next())
				{
					result = new SystemConfiguration();
					result.name= s.getString(2);
					result.value= s.getString(3);
					result.id= _id;
					putToCache(result);
				}
			}
			catch(Exception exc)
			{
				System.err.println(exc);
				exc.printStackTrace();
			}
			stmt.close();
		
		}
		catch (Exception ex)
		{
			System.err.println(ex);
			ex.printStackTrace();
		}
		return result;
	}

	/**
	 * returns boolean
	 */
	public boolean commit()
	{
		SaveStatement  stmt;

		try
		{
			stmt  = ConnectionManager.getValid().createStatement("_dbSystemConfiguration.commit");
			try
			{
				stmt.executeUpdate( "UPDATE SystemConfiguration set name= '"+toSQL(name)+"', value= '"+toSQL(value)+"' WHERE id='"+id+"'");
			}
			catch(Exception exc)
			{
				System.err.println(exc);
				exc.printStackTrace();
			}
			stmt.close();
		
		}
		catch (Exception ex)
		{
			System.err.println(ex);
			ex.printStackTrace();
		}
		return true;
	}


	/**
	 * returns ArrayList<SystemConfiguration>
	 */
	public static ArrayList getAll()
	{
		ArrayList result = new ArrayList();
		SaveStatement  stmt;

		try
		{
			stmt  = ConnectionManager.getValid().createStatement("_dbSystemConfiguration.getAll");
			try
			{
				ResultSet s = stmt.executeQuery( "SELECT id, name, value FROM SystemConfiguration order by generatedId desc");
				while(s.next())
				{
					String _tmpID = s.getString(1);
					SystemConfiguration newObject = (SystemConfiguration)getFromCache(_tmpID);
					if(newObject ==null)
					{
						newObject = new SystemConfiguration();
						newObject.name=s.getString(2);
						newObject.value=s.getString(3);
						newObject.id=_tmpID;
						putToCache(newObject);
					}
					result.add(newObject);
				}
			}
			catch(Exception exc)
			{
				System.err.println(exc);
				exc.printStackTrace();
			}
			stmt.close();
		
		}
		catch (Exception ex)
		{
			System.err.println(ex);
			ex.printStackTrace();
		}
		return result;
	}


	/**
	 * create a new object in the database
	 */
	static public SystemConfiguration createInstance( String  _name, String  _value )
	{
		SystemConfiguration result = null;
		SaveStatement  stmt;

		try
		{
			stmt  = ConnectionManager.getValid().createStatement("_dbSystemConfiguration.createInstance");
			try
			{
				String nextGUID = new java.rmi.server.UID().toString();
				stmt.executeUpdate( "INSERT INTO SystemConfiguration ( name, value, id) VALUES ( '"+toSQL(_name)+"',  '"+toSQL(_value)+"', '"+nextGUID+"')");
				result = new SystemConfiguration();
				result.name= _name;
				result.value= _value;
				result.id= nextGUID;
			}
			catch(Exception exc)
			{
				System.err.println(exc);
				exc.printStackTrace();
			}
			stmt.close();
		
		}
		catch (Exception ex)
		{
			System.err.println(ex);
			ex.printStackTrace();
		}
		return result;
	}


	/**
	 * create a new object in the database
	 */
	static public void newInstance( String  _name, String  _value )
	{
		SaveStatement  stmt;

		try
		{
			stmt  = ConnectionManager.getValid().createStatement("_dbSystemConfiguration.newInstance");
			try
			{
				String nextGUID = new java.rmi.server.UID().toString();
				stmt.executeUpdate( "INSERT INTO SystemConfiguration ( name, value, id) VALUES ( '"+toSQL(_name)+"',  '"+toSQL(_value)+"', '"+nextGUID+"')");
			}
			catch(Exception exc)
			{
				System.err.println(exc);
				exc.printStackTrace();
			}
			stmt.close();
		
		}
		catch (Exception ex)
		{
			System.err.println(ex);
			ex.printStackTrace();
		}
	}


	/**
	 * destroy a object in the database
	 */
	static public boolean destroyInstance( String  _key)
	{
		boolean result = false;
		SaveStatement  stmt;

		try
		{
			stmt  = ConnectionManager.getValid().createStatement("_dbSystemConfiguration.destroyInstance");
			try
			{
					stmt.executeUpdate( "DELETE FROM SystemConfiguration WHERE id='"+_key+"'");
					result = true;
			}
			catch(Exception exc)
			{
				System.err.println(exc);
				exc.printStackTrace();
			}
			stmt.close();
		
		}
		catch (Exception ex)
		{
			System.err.println(ex);
			ex.printStackTrace();
		}
		return result;
	}


	/**
	 * destroy ALL objects in the database
	 */
	static public boolean destroyAll()
	{
		boolean result = false;
		SaveStatement  stmt;

		try
		{
			stmt  = ConnectionManager.getValid().createStatement("_dbSystemConfiguration.destroyAll");
			try
			{
					stmt.executeUpdate("DELETE from SystemConfiguration" );
					result = true;
			}
			catch(Exception exc)
			{
				System.err.println(exc);
				exc.printStackTrace();
			}
			stmt.close();
		
		}
		catch (Exception ex)
		{
			System.err.println(ex);
			ex.printStackTrace();
		}
		return result;
	}


	/**
	 */
	public String toString()
	{
		StringBuffer result = new StringBuffer(1024);
		result.append(name);
		result.append("|");
		result.append(value);
		result.append("|");
		result.append(id);
		return result.toString();
	}


	/**
	 * init the class
	 */
	static
	{
		try
		{
			DatabaseMetaData dMeta = ConnectionManager.getValid().getMetaData ();
			ResultSet result;
			result=dMeta.getColumns(null,null,"SystemConfiguration","name");
			if(!result.next())
			{
				System.out.println("ERROR: installed DB-schema not compatible to java classes");
				System.out.println("       Attribute 'name' in table 'SystemConfiguration' missing");
			}
			result.close();
			result=dMeta.getColumns(null,null,"SystemConfiguration","value");
			if(!result.next())
			{
				System.out.println("ERROR: installed DB-schema not compatible to java classes");
				System.out.println("       Attribute 'value' in table 'SystemConfiguration' missing");
			}
			result.close();
			result=dMeta.getColumns(null,null,"SystemConfiguration","id");
			if(!result.next())
			{
				System.out.println("ERROR: installed DB-schema not compatible to java classes");
				System.out.println("       Attribute 'id' in table 'SystemConfiguration' missing");
			}
			result.close();
		}
		catch (Exception ex)
		{
		}
	}


}
