package de.shorti.baseknowledge.objects;

/**
 * Class generated by automatic ClassGenerator
 * Date: Mon May 06 12:18:40 GMT+02:00 2002
 */
import java.sql.ResultSet;

public class ContextPerformance extends _dbContextPerformance
{
	/**
	 *  Method:      findByContextRegistry(_dbContextRegistry _contextRegistry)
	 *  Description:
	 *  Returns:     ArrayList<ContextPerformance>
	 */
	public static long getDurationSummaryByContextRegistry(_dbContextRegistry _contextRegistry)
	{
		SaveStatement  stmt;
        long result=-1;
		try
		{
			stmt  = ConnectionManager.getValid().createStatement("ContextPerformance.findByContextRegistry");
			try
			{
				ResultSet s = stmt.executeQuery( "SELECT sum(duration), count(duration) FROM ContextPerformance WHERE contextRegistry_id='"+toSQL(((_contextRegistry==null)?"":_contextRegistry.getId()))+"'");
				if(s.next())
					result= s.getLong(1)/s.getLong(2);
			}
			catch(Exception exc)
			{
				System.err.println(exc);
			}
			stmt.close();

		}
		catch (Exception ex)
		{
			System.err.println(ex);
		}
		return result;
	}
}
