 INSERT INTO country (country,isocode) VALUES  ('Andorra','AD');
 INSERT INTO country (country,isocode) VALUES  ('United Arab Emirates','AE');
 INSERT INTO country (country,isocode) VALUES  ('Afghanistan','AF');
 INSERT INTO country (country,isocode) VALUES  ('Antigua And Barbuda','AG');
 INSERT INTO country (country,isocode) VALUES  ('Anguilla','AI');
 INSERT INTO country (country,isocode) VALUES  ('Albania','AL');
 INSERT INTO country (country,isocode) VALUES  ('Armenia','AM');
 INSERT INTO country (country,isocode) VALUES  ('Netherlands Antilles','AN');
 INSERT INTO country (country,isocode) VALUES  ('Angola','AO');
 INSERT INTO country (country,isocode) VALUES  ('Antarctica','AQ');
 INSERT INTO country (country,isocode) VALUES  ('Argentina','AR');
 INSERT INTO country (country,isocode) VALUES  ('American Samoa','AS');
 INSERT INTO country (country,isocode) VALUES  ('Austria','AT');
 INSERT INTO country (country,isocode) VALUES  ('Australia','AU');
 INSERT INTO country (country,isocode) VALUES  ('Aruba','AW');
 INSERT INTO country (country,isocode) VALUES  ('Azerbaijan','AZ');
 INSERT INTO country (country,isocode) VALUES  ('Bosnia and Herzegovina','BA');
 INSERT INTO country (country,isocode) VALUES  ('Barbados','BB');
 INSERT INTO country (country,isocode) VALUES  ('Bangladesh','BD');
 INSERT INTO country (country,isocode) VALUES  ('Belgium','BE');
 INSERT INTO country (country,isocode) VALUES  ('Burkina Faso','BF');
 INSERT INTO country (country,isocode) VALUES  ('Bulgaria','BG');
 INSERT INTO country (country,isocode) VALUES  ('Bahrain','BH');
 INSERT INTO country (country,isocode) VALUES  ('Burundi','BI');
 INSERT INTO country (country,isocode) VALUES  ('Benin','BJ');
 INSERT INTO country (country,isocode) VALUES  ('Bermuda','BM');
 INSERT INTO country (country,isocode) VALUES  ('Brunei Darussalam','BN');
 INSERT INTO country (country,isocode) VALUES  ('Bolivia','BO');
 INSERT INTO country (country,isocode) VALUES  ('Brazil','BR');
 INSERT INTO country (country,isocode) VALUES  ('Bahamas','BS');
 INSERT INTO country (country,isocode) VALUES  ('Bhutan','BT');
 INSERT INTO country (country,isocode) VALUES  ('Bouvet Island','BV');
 INSERT INTO country (country,isocode) VALUES  ('Botswana','BW');
 INSERT INTO country (country,isocode) VALUES  ('Belarus','BY');
 INSERT INTO country (country,isocode) VALUES  ('Belize','BZ');
 INSERT INTO country (country,isocode) VALUES  ('Canada','CA');
 INSERT INTO country (country,isocode) VALUES  ('Cocos (Keeling) Islands','CC');
 INSERT INTO country (country,isocode) VALUES  ('Central African Republic','CF');
 INSERT INTO country (country,isocode) VALUES  ('Congo','CG');
 INSERT INTO country (country,isocode) VALUES  ('Switzerland','CH');
 INSERT INTO country (country,isocode) VALUES  ('Cote d\´Ivoire','CI');
 INSERT INTO country (country,isocode) VALUES  ('Cook Islands','CK');
 INSERT INTO country (country,isocode) VALUES  ('Chile','CL');
 INSERT INTO country (country,isocode) VALUES  ('Cameroon','CM');
 INSERT INTO country (country,isocode) VALUES  ('China','CN');
 INSERT INTO country (country,isocode) VALUES  ('Colombia','CO');
 INSERT INTO country (country,isocode) VALUES  ('Costa Rica','CR');
 INSERT INTO country (country,isocode) VALUES  ('Cuba','CU');
 INSERT INTO country (country,isocode) VALUES  ('Cape Verde','CV');
 INSERT INTO country (country,isocode) VALUES  ('Christmas Island','CX');
 INSERT INTO country (country,isocode) VALUES  ('Cyprus','CY');
 INSERT INTO country (country,isocode) VALUES  ('Czech Republic','CZ');
 INSERT INTO country (country,isocode) VALUES  ('Germany','DE');
 INSERT INTO country (country,isocode) VALUES  ('Djibouti','DJ');
 INSERT INTO country (country,isocode) VALUES  ('Denmark','DK');
 INSERT INTO country (country,isocode) VALUES  ('Dominica','DM');
 INSERT INTO country (country,isocode) VALUES  ('Dominican Republic','DO');
 INSERT INTO country (country,isocode) VALUES  ('Algeria','DZ');
 INSERT INTO country (country,isocode) VALUES  ('Ecuador','EC');
 INSERT INTO country (country,isocode) VALUES  ('Estonia','EE');
 INSERT INTO country (country,isocode) VALUES  ('Egypt','EG');
 INSERT INTO country (country,isocode) VALUES  ('Western Sahara','EH');
 INSERT INTO country (country,isocode) VALUES  ('Eritrea','ER');
 INSERT INTO country (country,isocode) VALUES  ('Spain','ES');
 INSERT INTO country (country,isocode) VALUES  ('Ethiopia','ET');
 INSERT INTO country (country,isocode) VALUES  ('Europe (SSGFI only)','EU');
 INSERT INTO country (country,isocode) VALUES  ('Finland','FI');
 INSERT INTO country (country,isocode) VALUES  ('Fiji','FJ');
 INSERT INTO country (country,isocode) VALUES  ('Falkland Islands (Malvinas)','FK');
 INSERT INTO country (country,isocode) VALUES  ('Micronesia, Federated States Of','FM');
 INSERT INTO country (country,isocode) VALUES  ('Faeroe Islands','FO');
 INSERT INTO country (country,isocode) VALUES  ('France','FR');
 INSERT INTO country (country,isocode) VALUES  ('France, Metropolitan','FX');
 INSERT INTO country (country,isocode) VALUES  ('Gabon','GA');
 INSERT INTO country (country,isocode) VALUES  ('United Kingdom','GB (UK)');
 INSERT INTO country (country,isocode) VALUES  ('Grenada','GD');
 INSERT INTO country (country,isocode) VALUES  ('Georgia','GE');
 INSERT INTO country (country,isocode) VALUES  ('French Guiana','GF');
 INSERT INTO country (country,isocode) VALUES  ('Ghana','GH');
 INSERT INTO country (country,isocode) VALUES  ('Gibraltar','GI');
 INSERT INTO country (country,isocode) VALUES  ('Greenland','GL');
 INSERT INTO country (country,isocode) VALUES  ('Gambia','GM');
 INSERT INTO country (country,isocode) VALUES  ('Guinea','GN');
 INSERT INTO country (country,isocode) VALUES  ('Guadeloupe','GP');
 INSERT INTO country (country,isocode) VALUES  ('Equatorial Guinea','GQ');
 INSERT INTO country (country,isocode) VALUES  ('Greece','GR');
 INSERT INTO country (country,isocode) VALUES  ('South Georgia And The South Sandwich Isl','GS');
 INSERT INTO country (country,isocode) VALUES  ('Guatemala','GT');
 INSERT INTO country (country,isocode) VALUES  ('Guam','GU');
 INSERT INTO country (country,isocode) VALUES  ('Guinea-Bissau','GW');
 INSERT INTO country (country,isocode) VALUES  ('Guyana','GY');
 INSERT INTO country (country,isocode) VALUES  ('Hong Kong','HK');
 INSERT INTO country (country,isocode) VALUES  ('Heard And Mc Donald Islands','HM');
 INSERT INTO country (country,isocode) VALUES  ('Honduras','HN');
 INSERT INTO country (country,isocode) VALUES  ('Croatia (local name: Hrvatska)','HR');
 INSERT INTO country (country,isocode) VALUES  ('Haiti','HT');
 INSERT INTO country (country,isocode) VALUES  ('Hungary','HU');
 INSERT INTO country (country,isocode) VALUES  ('Indonesia','ID');
 INSERT INTO country (country,isocode) VALUES  ('Ireland','IE');
 INSERT INTO country (country,isocode) VALUES  ('International (SSGFI only)','II');
 INSERT INTO country (country,isocode) VALUES  ('Israel','IL');
 INSERT INTO country (country,isocode) VALUES  ('India','IN');
 INSERT INTO country (country,isocode) VALUES  ('British Indian Ocean Territory','IO');
 INSERT INTO country (country,isocode) VALUES  ('Iraq','IQ');
 INSERT INTO country (country,isocode) VALUES  ('Iran (Islamic Republic Of)','IR');
 INSERT INTO country (country,isocode) VALUES  ('Iceland','IS');
 INSERT INTO country (country,isocode) VALUES  ('Italy','IT');
 INSERT INTO country (country,isocode) VALUES  ('Jamaica','JM');
 INSERT INTO country (country,isocode) VALUES  ('Jordan','JO');
 INSERT INTO country (country,isocode) VALUES  ('Japan','JP');
 INSERT INTO country (country,isocode) VALUES  ('Kenya','KE');
 INSERT INTO country (country,isocode) VALUES  ('Kyrgyzstan','KG');
 INSERT INTO country (country,isocode) VALUES  ('Cambodia','KH');
 INSERT INTO country (country,isocode) VALUES  ('Kiribati','KI');
 INSERT INTO country (country,isocode) VALUES  ('Comoros','KM');
 INSERT INTO country (country,isocode) VALUES  ('Saint Kitts And Nevis','KN');
 INSERT INTO country (country,isocode) VALUES  ('Korea, Democratic People\´s Republic Of','KP');
 INSERT INTO country (country,isocode) VALUES  ('Korea, Republic Of','KR');
 INSERT INTO country (country,isocode) VALUES  ('Kuwait','KW');
 INSERT INTO country (country,isocode) VALUES  ('Cayman Islands','KY');
 INSERT INTO country (country,isocode) VALUES  ('Kazakhstan','KZ');
 INSERT INTO country (country,isocode) VALUES  ('Lao People\´s Democratic Republic','LA');
 INSERT INTO country (country,isocode) VALUES  ('Lebanon','LB');
 INSERT INTO country (country,isocode) VALUES  ('Saint Lucia','LC');
 INSERT INTO country (country,isocode) VALUES  ('Liechtenstein','LI');
 INSERT INTO country (country,isocode) VALUES  ('Sri Lanka','LK');
 INSERT INTO country (country,isocode) VALUES  ('Liberia','LR');
 INSERT INTO country (country,isocode) VALUES  ('Lesotho','LS');
 INSERT INTO country (country,isocode) VALUES  ('Lithuania','LT');
 INSERT INTO country (country,isocode) VALUES  ('Luxembourg','LU');
 INSERT INTO country (country,isocode) VALUES  ('Latvia','LV');
 INSERT INTO country (country,isocode) VALUES  ('Libyan Arab Jamahiriya','LY');
 INSERT INTO country (country,isocode) VALUES  ('Morocco','MA');
 INSERT INTO country (country,isocode) VALUES  ('Monaco','MC');
 INSERT INTO country (country,isocode) VALUES  ('Moldova, Republic Of','MD');
 INSERT INTO country (country,isocode) VALUES  ('Madagascar','MG');
 INSERT INTO country (country,isocode) VALUES  ('Marshall Islands','MH');
 INSERT INTO country (country,isocode) VALUES  ('Macedonia, The Former Yugoslav Republic','MK');
 INSERT INTO country (country,isocode) VALUES  ('Mali','ML');
 INSERT INTO country (country,isocode) VALUES  ('Myanmar','MM');
 INSERT INTO country (country,isocode) VALUES  ('Mongolia','MN');
 INSERT INTO country (country,isocode) VALUES  ('Macau','MO');
 INSERT INTO country (country,isocode) VALUES  ('Northern Mariana Islands','MP');
 INSERT INTO country (country,isocode) VALUES  ('Martinique','MQ');
 INSERT INTO country (country,isocode) VALUES  ('Mauritania','MR');
 INSERT INTO country (country,isocode) VALUES  ('Montserrat','MS');
 INSERT INTO country (country,isocode) VALUES  ('Malta','MT');
 INSERT INTO country (country,isocode) VALUES  ('Mauritius','MU');
 INSERT INTO country (country,isocode) VALUES  ('Maldives','MV');
 INSERT INTO country (country,isocode) VALUES  ('Malawi','MW');
 INSERT INTO country (country,isocode) VALUES  ('Mexico','MX');
 INSERT INTO country (country,isocode) VALUES  ('Malaysia','MY');
 INSERT INTO country (country,isocode) VALUES  ('Mozambique','MZ');
 INSERT INTO country (country,isocode) VALUES  ('Namibia','NA');
 INSERT INTO country (country,isocode) VALUES  ('New Caledonia','NC');
 INSERT INTO country (country,isocode) VALUES  ('Niger','NE');
 INSERT INTO country (country,isocode) VALUES  ('Norfolk Island','NF');
 INSERT INTO country (country,isocode) VALUES  ('Nigeria','NG');
 INSERT INTO country (country,isocode) VALUES  ('Nicaragua','NI');
 INSERT INTO country (country,isocode) VALUES  ('Netherlands','NL');
 INSERT INTO country (country,isocode) VALUES  ('Norway','NO');
 INSERT INTO country (country,isocode) VALUES  ('Nepal','NP');
 INSERT INTO country (country,isocode) VALUES  ('Nauru','NR');
 INSERT INTO country (country,isocode) VALUES  ('Niue','NU');
 INSERT INTO country (country,isocode) VALUES  ('New Zealand','NZ');
 INSERT INTO country (country,isocode) VALUES  ('Oman','OM');
 INSERT INTO country (country,isocode) VALUES  ('Panama','PA');
 INSERT INTO country (country,isocode) VALUES  ('Peru','PE');
 INSERT INTO country (country,isocode) VALUES  ('French Polynesia','PF');
 INSERT INTO country (country,isocode) VALUES  ('Papua New Guinea','PG');
 INSERT INTO country (country,isocode) VALUES  ('Philippines','PH');
 INSERT INTO country (country,isocode) VALUES  ('Pakistan','PK');
 INSERT INTO country (country,isocode) VALUES  ('Poland','PL');
 INSERT INTO country (country,isocode) VALUES  ('St. Pierre And Miquelon','PM');
 INSERT INTO country (country,isocode) VALUES  ('Pitcairn','PN');
 INSERT INTO country (country,isocode) VALUES  ('Puerto Rico','PR');
 INSERT INTO country (country,isocode) VALUES  ('Portugal','PT');
 INSERT INTO country (country,isocode) VALUES  ('Palau','PW');
 INSERT INTO country (country,isocode) VALUES  ('Paraguay','PY');
 INSERT INTO country (country,isocode) VALUES  ('Qatar','QA');
 INSERT INTO country (country,isocode) VALUES  ('Reunion','RE');
 INSERT INTO country (country,isocode) VALUES  ('Romania','RO');
 INSERT INTO country (country,isocode) VALUES  ('Russian Federation','RU');
 INSERT INTO country (country,isocode) VALUES  ('Rwanda','RW');
 INSERT INTO country (country,isocode) VALUES  ('Saudi Arabia','SA');
 INSERT INTO country (country,isocode) VALUES  ('Solomon Islands','SB');
 INSERT INTO country (country,isocode) VALUES  ('Seychelles','SC');
 INSERT INTO country (country,isocode) VALUES  ('Sudan','SD');
 INSERT INTO country (country,isocode) VALUES  ('Sweden','SE');
 INSERT INTO country (country,isocode) VALUES  ('Singapore','SG');
 INSERT INTO country (country,isocode) VALUES  ('St. Helena','SH');
 INSERT INTO country (country,isocode) VALUES  ('Slovenia','SI');
 INSERT INTO country (country,isocode) VALUES  ('Svalbard And Jan Mayen Islands','SJ');
 INSERT INTO country (country,isocode) VALUES  ('Slovakia (Slovak Republic)','SK');
 INSERT INTO country (country,isocode) VALUES  ('Sierra Leone','SL');
 INSERT INTO country (country,isocode) VALUES  ('San Marino','SM');
 INSERT INTO country (country,isocode) VALUES  ('Senegal','SN');
 INSERT INTO country (country,isocode) VALUES  ('Somalia','SO');
 INSERT INTO country (country,isocode) VALUES  ('Suriname','SR');
 INSERT INTO country (country,isocode) VALUES  ('Sao Tome And Principe','ST');
 INSERT INTO country (country,isocode) VALUES  ('El Salvador','SV');
 INSERT INTO country (country,isocode) VALUES  ('Syrian Arab Republic','SY');
 INSERT INTO country (country,isocode) VALUES  ('Swaziland','SZ');
 INSERT INTO country (country,isocode) VALUES  ('Turks And Caicos Islands','TC');
 INSERT INTO country (country,isocode) VALUES  ('Chad','TD');
 INSERT INTO country (country,isocode) VALUES  ('French Southern Territories','TF');
 INSERT INTO country (country,isocode) VALUES  ('Togo','TG');
 INSERT INTO country (country,isocode) VALUES  ('Thailand','TH');
 INSERT INTO country (country,isocode) VALUES  ('Tajikistan','TJ');
 INSERT INTO country (country,isocode) VALUES  ('Tokelau','TK');
 INSERT INTO country (country,isocode) VALUES  ('Turkmenistan','TM');
 INSERT INTO country (country,isocode) VALUES  ('Tunisia','TN');
 INSERT INTO country (country,isocode) VALUES  ('Tonga','TO');
 INSERT INTO country (country,isocode) VALUES  ('East Timor','TP');
 INSERT INTO country (country,isocode) VALUES  ('Turkey','TR');
 INSERT INTO country (country,isocode) VALUES  ('Trinidad And Tobago','TT');
 INSERT INTO country (country,isocode) VALUES  ('Tuvalu','TV');
 INSERT INTO country (country,isocode) VALUES  ('Taiwan, Province Of China','TW');
 INSERT INTO country (country,isocode) VALUES  ('Tanzania, United Republic Of','TZ');
 INSERT INTO country (country,isocode) VALUES  ('Ukraine','UA');
 INSERT INTO country (country,isocode) VALUES  ('Uganda','UG');
 INSERT INTO country (country,isocode) VALUES  ('United States Minor Outlying Islands','UM');
 INSERT INTO country (country,isocode) VALUES  ('United States','US');
 INSERT INTO country (country,isocode) VALUES  ('Uruguay','UY');
 INSERT INTO country (country,isocode) VALUES  ('Uzbekistan','UZ');
 INSERT INTO country (country,isocode) VALUES  ('Vatican City State (Holy See)','VA');
 INSERT INTO country (country,isocode) VALUES  ('Saint Vincent And The Grenadines','VC');
 INSERT INTO country (country,isocode) VALUES  ('Venezuela','VE');
 INSERT INTO country (country,isocode) VALUES  ('Virgin Islands (British)','VG');
 INSERT INTO country (country,isocode) VALUES  ('Virgin Islands (U.S.)','VI');
 INSERT INTO country (country,isocode) VALUES  ('Viet Nam','VN');
 INSERT INTO country (country,isocode) VALUES  ('Vanuatu','VU');
 INSERT INTO country (country,isocode) VALUES  ('Wallis And Futuna Islands','WF');
 INSERT INTO country (country,isocode) VALUES  ('Samoa','WS');
 INSERT INTO country (country,isocode) VALUES  ('Yemen','YE');
 INSERT INTO country (country,isocode) VALUES  ('Mayotte','YT');
 INSERT INTO country (country,isocode) VALUES  ('Yugoslavia','YU');
 INSERT INTO country (country,isocode) VALUES  ('South Africa','ZA');
 INSERT INTO country (country,isocode) VALUES  ('Zambia','ZM');
 INSERT INTO country (country,isocode) VALUES  ('Zaire','ZR');
 INSERT INTO country (country,isocode) VALUES  ('Zimbabwe','ZW');
 