package de.shorti.baseknowledge;

/**
 * short-i Class generated by automatic ClassGenerator
 * Date: Mon Apr 15 18:21:59 GMT+02:00 2002
 */
import de.shorti.*;
import java.util.HashSet;
import java.util.ArrayList;
import java.util.Iterator;
import java.sql.*;
import de.shorti.util.basic.*;
import de.shorti.util.search.fuzzy.*;
import de.shorti.baseknowledge.objects.Country;



public class CountryNameCatalog
{
	static final int MIN_HIT_PERCENTAGE = 30;
	static TraceDispatcher  trace = TraceFactory.getTraceDispatcher();
	static FuzzySearch search = new FuzzySearch();


	/**
	* returns ArrayList<Keyword>
	*/
	static public ArrayList find(String s)
	{
		ArrayList tmp    = search.find(s,MIN_HIT_PERCENTAGE);
		ArrayList result = new ArrayList();
		// the first Item is the best hit....move only the 'top ten'
		// to the result set
		//
		int lastHitPercentage = 0;
		Iterator iter = tmp.iterator();
		while(iter.hasNext())
		{
			Keyword k = (Keyword)iter.next();
			if(k.m_percentage >= lastHitPercentage )
			{
				result.add(k);
				lastHitPercentage = k.m_percentage;
			}
			else
			{
				return result;
			}
		}
		return result;
	}


	/**
	* load the keywords in the FuzzySearch engine
	*/
	static
	{
		ArrayList   objects    = Country.getAll();
		Iterator iter       = objects.iterator();
		HashSet  newCatalog = new HashSet();
		Country object = null;

		while(iter.hasNext())
		{
			object = (Country)iter.next();
			newCatalog.add(object.getName());
		}
		search.setCatalog(newCatalog);

	}

}
